// --- YAML export ---
function fmtA(a) { return (Math.round(a * 10) / 10).toString(); }
// fromMs: where the show's clock is parked. A file built from a parked clock
// starts at THAT keyframe, not at the first one — the robot is already standing
// at the pose you clicked, and sending it back to keyframe 0 first is a long
// unplanned sweep across the rig. The user, 2026-08-28: *my body of robot will
// broke it hit other thing that i don't want if it warp to pose 1*.
// The skipped keyframes are still WALKED: `speed` is state, so a file that
// starts in the middle must carry the speed in force there, or the rest of the
// show runs at the wrong one.
function buildYaml(fromMs) {
  const name = ($("seqName").value || "sequence").trim().replace(/[^\w.-]+/g, "_");
  const lines = [
    "# generated by Nong Studio (code/nong/main_python_set_nong)",
    "# pose order: " + JOINT_NAMES.join(" ") + "  (joint deg, T = ms)",
    "name: " + name,
    "loop: " + ($("loopChk").checked ? "true" : "false"),
    "steps:",
  ];
  // The show speed belongs to the SEQUENCE, not to the editor: it is written
  // as the first step so the module applies it when this file starts. That
  // also makes a chain deterministic — sequence B sets its own speed instead
  // of inheriting whatever A happened to leave the module on.
  // One source of truth: the editor reads this step back when re-editing.
  const seqDps = Math.round(speedDps());
  const K0 = playKeys();
  // where this file starts. 0 (the whole show) unless a clock was handed in.
  const from = fromMs > 0 ? keyIndexAtMs(fromMs) : 0;
  // the speed in force at that point, which is what the leading step must be
  let cur = seqDps;
  for (let s = 0; s < from && s < K0.length; s++) cur = Math.round(K0[s].dps || seqDps);
  lines.push(`  - speed: ${cur}`);
  // suspended keyframes are left out entirely — the robot never sees them
  playKeys().forEach((k, i) => {
    if (i < from) return;      // walked for state above, never written as motion
    // a move with its own speed emits a speed step first, and the next move
    // without one puts the sequence speed back — so the file reads exactly as
    // the timeline runs, and the module's speed tracks it move by move.
    // No i>0 exemption: an override on the FIRST move must be written too,
    // or the robot plays it at the sequence speed the timeline never showed.
    const want = Math.round(k.dps || speedDps());
    if (want !== cur) { lines.push(`  - speed: ${want}`); cur = want; }
    // The name you gave the move, as a comment above it. A comment so
    // every existing player still reads the file unchanged — the
    // firmware ignores it, and a person opening the YAML can see what
    // each step was meant to be.
    if (k.name) lines.push(`  # ${k.name.replace(/[\r\n]/g, " ")}`);
    // The cues this keyframe carried in, written back where they came from —
    // before the move, the same order the file had them in. Without this an
    // edit-and-export silently threw the show's music away.
    (k.cues || []).forEach(c => lines.push(`  - ${c}`));
    // The FIRST move written is the only one whose starting point the file
    // cannot know — the robot is wherever it is standing, not where the
    // timeline says. Give it at least the time that distance really needs, so
    // a resumed show can never begin with a lunge. Never faster, only slower.
    const t = (i === from && from > 0) ? Math.max(k.t, minTime(pose, k.pose)) : k.t;
    lines.push(`  - pose: "${k.pose.map(fmtA).join(" ")} T ${t}"` +
               (i === 0 ? "    # start pose"
                        : i === from ? "    # resumed from here" : ""));
    if (k.hold > 0) lines.push(`  - wait: ${k.hold}`);
    (k.cuesAfter || []).forEach(c => lines.push(`  - ${c}`));
  });
  const next = ($("seqNext").value || "").trim().replace(/[^\w.-]+/g, "");
  if (next) {
    // chain: when this sequence ends the module starts that one, so a show can
    // be built from short files instead of one long one
    lines.splice(4, 0, "next: " + (next.endsWith(".yaml") ? next : next + ".yaml"));
  }
  return { name, yaml: lines.join("\n") + "\n" };
}
// Guard on what will actually be WRITTEN, not on how many keyframes exist:
// with everything suspended the timeline is full but the file would carry no
// moves at all, and the robot would "run" a sequence that does nothing.
function nothingToWrite(where) {
  if (playKeys().length) return false;
  $(where).textContent = keys.length
    ? "every keyframe is suspended — un-suspend at least one to export or upload"
    : "no keyframes yet";
  return true;
}
async function exportYaml() {
  if (nothingToWrite("tlStat")) return;
  const { name, yaml } = buildYaml();
  // Every failure path must SAY something: an unhandled rejection here left
  // the old status line standing, and a silent export reads as saved work.
  try {
    const r = await fetch("/api/export", {
      method: "POST", body: JSON.stringify({ name: name + ".yaml", yaml }),
    });
    const j = await r.json();
    if (!r.ok || !j.ok) throw new Error((j && j.error) || ("HTTP " + r.status));
    // j.file echoes a name that was typed into this page; as text, never
    // as markup.
    $("tlStat").textContent =
      `saved ${j.file} in the sequences/ folder — copy it to the SD card /moves/, ` +
      `then pick it on the module website (Sequences card) or send: MOVE ${j.file}`;
  } catch (e) {
    $("tlStat").textContent = "export failed — the hub is not answering, or "
      + "refused the name. Nothing was written. " + (e.message || e);
    notice($("tlStat").textContent);
  }
  refreshSeqs();
}
