// GENERATED by firmware/tools/gen_tables.py from servos.json
// Do NOT edit this file — edit the JSON and rebuild.

#pragma once
#include <Arduino.h>

// One servo, exactly as config/servos.json describes it. `range` is the
// SERVO's own travel — not the joint's limits, which are per robot (LIMIT).
struct ServoPreset {
    const char* id;
    const char* label;
    int   pulseMin;
    int   pulseMax;
    float maxDps;
    float travelDeg;
    int   frameHz;
};

static const ServoPreset SERVO_PRESETS[] = {
    { "mg90s",       "MG90S",                 500,  2400,  400.0f,  180.0f,   50 },
    { "pdi1181mg",   "PDI-1181MG",            500,  2500,  375.0f,  270.0f,   50 },
    { "tiankong35",  "TianKongRC 35kg",       500,  2500,  250.0f,  270.0f,   50 },
    { "generic180",  "generic 180",           500,  2500,  300.0f,  180.0f,   50 },
    { "generic270",  "generic 270",           500,  2500,  300.0f,  270.0f,   50 },
};
static const int SERVO_PRESET_COUNT =
    sizeof(SERVO_PRESETS) / sizeof(SERVO_PRESETS[0]);

// Look one up by the name the SERVO command takes; nullptr when unknown.
inline const ServoPreset* findServoPreset(const String& id) {
    for (int i = 0; i < SERVO_PRESET_COUNT; i++)
        if (id.equalsIgnoreCase(SERVO_PRESETS[i].id)) return &SERVO_PRESETS[i];
    return nullptr;
}

// "mg90s pdi1181mg tiankong35 ..." — for the command's own help text, so it
// can never list something the table does not have.
inline String servoPresetNames() {
    String s;
    for (int i = 0; i < SERVO_PRESET_COUNT; i++) {
        if (i) s += ' ';
        s += SERVO_PRESETS[i].id;
    }
    return s;
}
