#!/usr/bin/env python3
"""Publish the runnable app to its own branch, with nothing else in it.

    python tools/make_app_branch.py            build the branch locally
    python tools/make_app_branch.py --push     ...and push it

Asked for on 2026-08-19: a branch to download that holds only the app, so
another PC can run the hub without cloning the whole project.

WHY A SCRIPT AND NOT A HAND-MADE BRANCH
---------------------------------------
A branch that duplicates files drifts from the one it copied. This project has
already been bitten by exactly that - a stale copy of the plan inside .staging,
a day old, telling a reader that finished work was still to do. So the branch
is GENERATED: every publish rebuilds it from the current tree, with no history
to go stale and nothing to remember to update.

WHAT GOES IN, AND WHY EACH ONE
------------------------------
Since A15-1 the exe carries its own pages, so this branch is ONE program and a
README - nothing to install, no folders that must stay beside it, and no Python
on the machine that runs it. Proven by running the exe alone in an empty
folder: it served the hub, the shared stylesheet, Studio and the help app.

    MiceHub.exe                    the hub, and everything it serves
    README.md                      how to get just this, and how to run it

Deliberately NOT included: the firmware sources, the QC suite, the plan, the
build tooling. A PC that only runs the hub needs none of them - and leaving
firmware images out means this branch cannot flash a board over a cable, which
the README says out loud rather than letting someone discover it.
"""
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if ROOT.name == ".staging":
    ROOT = ROOT.parent
BRANCH = "app"

# (source, destination-in-branch). Directories are copied whole.
PARTS = [
    ("main_python/MiceHub.exe", "MiceHub.exe"),
]

README = """# Mice hub — the app only

This branch holds **just the program**, so a PC that only needs to run the hub
does not have to download the whole project. It is generated by
`tools/make_app_branch.py` on the `main` branch; nothing here is edited by hand.

## Get it

Only this branch, without the history of the project:

```
git clone --branch app --depth 1 https://github.com/Mannaja78520/final_proj_mice.git mice-app
```

Or, if you already have the project and want only this folder:

```
git fetch origin app
git checkout origin/app -- MiceHub.exe
```

## Run it

```
main_python\\MiceHub.exe
```

It prints three ways in, and opens the first one for you:

```
this PC   -> http://127.0.0.1:8642/
same WiFi -> http://<this-pc>:8642/     from a phone or another laptop
by name   -> http://mice.local:8642/
```

The first run makes a password and writes it to
`main_python/hub_password.txt`. Read it there. Reading the hub needs no
password; anything that CHANGES something does.

## What this can and cannot do

It can find modules on the network and over a cable, drive them, run shows,
open each module's own website, and update a module **over WiFi**.

It cannot **flash a board over a cable**: that needs `esptool`, which comes
with PlatformIO, and neither is here. Two ways round it, both already built:
update over WiFi from this PC, or have a PC that does have the toolchain send
the firmware across for this one to write.

Keep the folder layout as it is. The program looks for its pages beside itself
(`main_python/web`) and one level up (`shared/web`); moving the exe on its own
gives you a hub with no styling and no Studio.
"""


def run(*args, **kw):
    return subprocess.run(args, cwd=str(ROOT), capture_output=True, text=True, **kw)


def main(argv):
    push = "--push" in argv
    missing = [src for src, _dst in PARTS if not (ROOT / src).exists()]
    if missing:
        print("cannot publish, these are not built yet:")
        for m in missing:
            print("   ", m)
        if "MiceHub.exe" in " ".join(missing):
            print("\nbuild it with:\n  python -m PyInstaller --onefile "
                  "--icon main_python/nong.ico --name MiceHub main_python/main.py")
        return 1

    with tempfile.TemporaryDirectory(prefix="mice_app_") as tmp:
        work = Path(tmp) / "tree"
        work.mkdir()
        import shutil
        for src, dst in PARTS:
            s, d = ROOT / src, work / dst
            d.parent.mkdir(parents=True, exist_ok=True)
            if s.is_dir():
                shutil.copytree(s, d)
            else:
                shutil.copy2(s, d)
        (work / "README.md").write_text(README, encoding="utf-8", newline="")

        # Built with git plumbing so the checkout in front of you is never
        # touched: no branch switch, no stash, nothing to put back if this
        # fails halfway.
        index = Path(tmp) / "index"
        env = {"GIT_INDEX_FILE": str(index), "GIT_WORK_TREE": str(work)}
        import os
        e = dict(os.environ, **env)
        # --git-dir keeps this pointed at the real repository while the work
        # tree is the temporary folder: git run from inside a temp dir has no
        # repository to write objects into.
        gitdir = str(ROOT / ".git")
        e["GIT_DIR"] = gitdir
        subprocess.run(["git", "add", "-A", "-f", "."],
                       cwd=str(work), env=e, check=True)
        tree = subprocess.run(["git", "write-tree"], cwd=str(work), env=e,
                              capture_output=True, text=True, check=True).stdout.strip()
        head = run("git", "rev-parse", "--short", "HEAD").stdout.strip()
        msg = ("The app, built from %s\n\nGenerated by tools/make_app_branch.py. "
               "Nothing here is edited by hand.\n" % head)
        commit = subprocess.run(["git", "commit-tree", tree, "-m", msg],
                                cwd=str(work), env=e, capture_output=True,
                                text=True, check=True).stdout.strip()
        run("git", "update-ref", "refs/heads/" + BRANCH, commit)

    size = sum(f.stat().st_size for f in (ROOT / "main_python").rglob("*")
               if f.is_file() and f.name == "MiceHub.exe")
    print("branch %s now points at %s" % (BRANCH, commit[:10]))
    print("   the exe alone is %.1f MB, and every publish adds another copy to "
          "the repo\n   history - which is the real cost of a branch rather "
          "than a release" % (size / 1048576.0))
    if push:
        r = run("git", "push", "--force", "origin", BRANCH)
        print((r.stdout + r.stderr).strip()[-300:])
    else:
        print("   not pushed. Add --push when you want it on GitHub.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
