"""The subsystem map: which system owns a file, and each system's header page.

    python tools/systems.py which main_python/mdns.py   owner, header, checks
    python tools/systems.py checks hub-net               checks that test it
    python tools/systems.py build                        rewrite docs/systems/
    python tools/systems.py verify                       what check_systems runs

Asked 2026-09-21 (A26-76): every AI - Claude, Codex, Gemini - should read one
short header instead of the whole tree, change one subsystem and check only
that. The map is DATA in docs/systems.json; the header pages in docs/systems/
are generated below a marker, so the file lists in them cannot go stale. The
part above the marker is written by people (purpose, rules, traps) and kept.

Ownership: the most specific pattern wins, like a closer #include. A folder
pattern ends in "/", anything else is a glob on the path. Two systems
claiming a file with EQUALLY specific patterns is an error, and so is a file
nobody owns.
"""
import json
import os
import re
import sys
from pathlib import Path

CODE = Path(__file__).resolve().parent.parent
MARK = "<!-- generated by tools/systems.py below this line - edit docs/systems.json -->"


def load(code=CODE):
    return json.loads((Path(code) / "docs" / "systems.json").read_text(encoding="utf-8"))


def _skipped(rel, reg):
    parts = rel.split("/")
    for x in reg.get("exclude") or []:
        if x.endswith("/"):
            if any(p == x[:-1] for p in parts[:-1]) or rel.startswith(x):
                return True
        elif any(p.startswith(x) for p in parts):
            return True
    if parts[-1] in (reg.get("excludeNames") or []):
        return True
    return Path(rel).suffix.lower() in (reg.get("excludeExt") or [])


def files(code=CODE, reg=None):
    """Every file the map has to account for, as posix paths from code/."""
    reg = reg or load(code)
    out = []
    for parent, dirs, names in os.walk(code):
        rel_dir = Path(parent).relative_to(code).as_posix()
        dirs[:] = [d for d in dirs
                   if not _skipped((rel_dir + "/" + d + "/x").lstrip("./"), reg)]
        for n in names:
            rel = (Path(parent) / n).relative_to(code).as_posix()
            if not _skipped(rel, reg):
                out.append(rel)
    return sorted(out)


def _glob(pat):
    # "*" stays inside one folder: "*.txt" is the root's .txt files, not all
    return re.compile("^" + re.escape(pat).replace(r"\*", "[^/]*") + "$")


def _score(rel, pat):
    """How specifically `pat` names `rel`, or -1 if it does not."""
    if pat.endswith("/"):
        return len(pat) if rel.startswith(pat) else -1
    if rel == pat:
        return 10000 + len(pat)                  # an exact name beats any folder
    return len(pat.replace("*", "")) if _glob(pat).match(rel) else -1


def owners(rel, reg):
    """[(score, system id)] best first."""
    got = []
    for s in reg["systems"]:
        best = max((_score(rel, p) for p in s["files"]), default=-1)
        if best >= 0:
            got.append((best, s["id"]))
    return sorted(got, reverse=True)


def owner(rel, reg=None):
    got = owners(rel, reg or load())
    return got[0][1] if got else None


# Too common to find a system by: main.py or index.html is named everywhere.
GENERIC = {"index", "app", "service", "main", "style", "help", "config", "readme",
           "__init__", "template", "data", "utils", "common", "claude", "promt"}
_texts = {}


def _check_texts(code):
    if code not in _texts:
        _texts[code] = [(c.stem, c.read_text(encoding="utf-8", errors="replace").lower())
                        for c in sorted((Path(code) / "qc" / "checks").glob("check_*.py"))]
    return _texts[code]


def checks_for(sid, code=CODE, reg=None, mine=None):
    """Checks whose source names a file of this system: its path, its file
    name, or (for a distinctive name) the module it imports as."""
    reg = reg or load(code)
    if mine is None:
        mine = [f for f in files(code, reg) if owner(f, reg) == sid]
    needles = set()
    for f in mine:
        p = Path(f)
        needles.add(f.lower())
        if p.stem.lower() not in GENERIC and len(p.stem) >= 4:
            needles.add(p.name.lower())
            if len(p.stem) >= 6 and p.suffix == ".py":
                needles.add("import " + p.stem.lower())
    return [stem for stem, text in _check_texts(code)
            if stem != "check_scope" and any(n in text for n in needles)]


def owned(code=CODE, reg=None):
    """{system id: [its files]} plus the problems found while sorting them."""
    reg = reg or load(code)
    out = {s["id"]: [] for s in reg["systems"]}
    bad = []
    for f in files(code, reg):
        got = owners(f, reg)
        if not got:
            bad.append("nobody owns %s - add it to a system in docs/systems.json" % f)
            continue
        if len(got) > 1 and got[0][0] == got[1][0]:
            bad.append("%s is claimed equally by %s and %s" % (f, got[0][1], got[1][1]))
        out[got[0][1]].append(f)
    return out, bad


def verify(code=CODE):
    """Problems with the map, as plain sentences. Empty means it is sound."""
    reg = load(code)
    ids = [s["id"] for s in reg["systems"]]
    bad = []
    if len(ids) != len(set(ids)):
        bad.append("a system id is used twice")
    for s in reg["systems"]:
        for d in s.get("depends") or []:
            if d not in ids:
                bad.append("%s depends on %s, which is not a system" % (s["id"], d))
    mine, problems = owned(code, reg)
    bad += problems
    for s in reg["systems"]:
        page = Path(code) / "docs" / "systems" / (s["id"] + ".md")
        if not page.is_file():
            bad.append("%s has no header page - run: python tools/systems.py build" % s["id"])
        elif (page.read_text(encoding="utf-8").split(MARK, 1)[-1]
              != _generated(s, code, reg, mine[s["id"]])):
            bad.append("docs/systems/%s.md is out of date - run: python tools/systems.py build"
                       % s["id"])
    return bad


def _generated(s, code, reg, mine):
    users = [o["id"] for o in reg["systems"] if s["id"] in (o.get("depends") or [])]
    checks = checks_for(s["id"], code, reg, mine)
    lines = ["", "", "## Files (%d)" % len(mine), ""]
    lines += ["- `%s`" % f for f in mine] or ["- (none yet)"]
    lines += ["", "## Depends on", ""]
    lines += ["- [%s](%s.md)" % (d, d) for d in s.get("depends") or []] or ["- nothing"]
    lines += ["", "## Used by", ""]
    lines += ["- [%s](%s.md)" % (u, u) for u in users] or ["- nothing"]
    lines += ["", "## Checks that test it (%d)" % len(checks), ""]
    lines += ["- `%s`" % c for c in checks] or ["- none name its files yet - add one"]
    lines += ["", "Run them: `python qc/run_qc.py --no-build %s`" % " ".join(checks[:40])
              if checks else "", ""]
    return "\n".join(lines)


def build(code=CODE):
    reg = load(code)
    out_dir = Path(code) / "docs" / "systems"
    out_dir.mkdir(parents=True, exist_ok=True)
    index = ["# Systems", "",
             "Find the file you are changing below, read that ONE page, and stay in it.",
             "`python tools/systems.py which <path>` answers the same question.", "",
             "Generated from `docs/systems.json` by `tools/systems.py build`.", "",
             "| system | what it is |", "|---|---|"]
    mine, _bad = owned(code, reg)
    for s in reg["systems"]:
        page = out_dir / (s["id"] + ".md")
        head = ("# %s\n\n%s\n\n## Rules and traps\n\n- (write the non-obvious ones here "
                "when this system is next touched)\n\n" % (s["id"], s["summary"]))
        if page.is_file():
            head = page.read_text(encoding="utf-8").split(MARK, 1)[0]
        body = head + MARK + _generated(s, code, reg, mine[s["id"]])
        with open(page, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(body)
        index.append("| [%s](%s.md) | %s |" % (s["id"], s["id"], s["summary"]))
    with open(out_dir / "README.md", "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(index) + "\n")


def main(argv):
    if not argv or argv[0] not in ("which", "checks", "build", "verify"):
        print(__doc__)
        return 2
    if argv[0] == "build":
        build()
        print("docs/systems/ rebuilt")
        return 0
    if argv[0] == "verify":
        bad = verify()
        print("\n".join(bad) or "the system map is sound")
        return 1 if bad else 0
    reg = load()
    if argv[0] == "which":
        rel = Path(argv[1]).resolve().relative_to(CODE).as_posix() \
            if Path(argv[1]).exists() else argv[1].replace("\\", "/")
        sid = owner(rel, reg)
        if not sid:
            print("nobody owns %s" % rel)
            return 1
        print("%s -> %s\nheader: docs/systems/%s.md" % (rel, sid, sid))
        return 0
    print(" ".join(checks_for(argv[1], reg=reg)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
