// GENERATED by firmware/tools/gen_tables.py from commands.json
// Do NOT edit this file — edit the JSON and rebuild.

#pragma once
#include <Arduino.h>

// One command, as config/commands.json declares it. The handlers live where
// they always did; this is the table HELP prints and QC checks against, so a
// command cannot quietly exist without being documented.
struct CommandDoc {
    const char* name;
    const char* scope;      // core | lift | nong
    const char* args;
    const char* help;
    bool        query;      // reports only, changes nothing
};

static const CommandDoc COMMAND_DOCS[] = {
    { "PING",    "core",  "",                                    "answer id, name and type — safe to broadcast",                  true },
    { "INFO",    "core",  "",                                    "one-line status JSON",                                          true },
    { "HELP",    "core",  "[<command>]",                         "list commands, or explain one",                                 true },
    { "SET",     "core",  "ID|NAME|TYPE|WIFI …",                 "identity, module type and radio mode",                          false },
    { "PEERS",   "core",  "",                                    "the other modules this one can see, as JSON",                   true },
    { "REACH",   "core",  "<ip|name|id> <command>",              "run a command on another module through this one and return its reply", false },
    { "WIFI",    "core",  "[ON|OFF|AP|RETRY|SCAN|CLEAR]",        "radio state, and change it live — never needs a reboot",        true },
    { "CFG",     "core",  "[<key> <value>|CLEAR]",               "settings stored on the chip; no args lists them",               false },
    { "PIN",     "core",  "<name> <gpio>|VALID|CLEAR",           "wire a function to a GPIO (reboot to apply)",                   false },
    { "PIN?",    "core",  "",                                    "the current hardware pin map, as JSON",                         true },
    { "PINS",    "core",  "",                                    "alias of PIN? — the current pin map",                           true },
    { "PINS?",   "core",  "",                                    "alias of PIN? — the current pin map",                           true },
    { "FILES",   "core",  "[<dir>]",                             "list SD files as JSON",                                         true },
    { "FBEGIN",  "core",  "<file>",                              "start writing an SD file over this channel",                    false },
    { "FDATA",   "core",  "<base64>",                            "append a chunk (≤120 bytes so it fits an RS485 frame)",         false },
    { "FEND",    "core",  "",                                    "finish the write",                                              false },
    { "FREAD",   "core",  "<file> <off> <n>",                    "read n bytes from an SD file as base64",                        true },
    { "FDEL",    "core",  "<file>",                              "delete an SD file",                                             false },
    { "MOVE",    "core",  "<file>|STOP",                         "run a /moves sequence from the card, or stop it",               false },
    { "AUTH",    "core",  "<user> <pass>",                       "check a Setup-page login",                                      true },
    { "USER",    "core",  "LIST|ADD|DEL|PASS …",                 "accounts stored on the board",                                  false },
    { "REBOOT",  "core",  "",                                    "restart about a second later",                                  false },
    { "UP",      "lift",  "",                                    "run up until the limit switch or STOP",                         false },
    { "DOWN",    "lift",  "",                                    "run down until the limit switch or STOP",                       false },
    { "STOP",    "lift",  "",                                    "stop, and cancel any GOTO",                                     false },
    { "HOME",    "lift",  "",                                    "seek the bottom limit and zero the encoder",                    false },
    { "GOTO",    "lift",  "<stage>",                             "go to a stage, homing first if the position is unknown",        false },
    { "STAGE",   "lift",  "",                                    "alias of STAGE?",                                               true },
    { "STAGE?",  "lift",  "",                                    "which stage it is at, or -1 if not homed",                      true },
    { "SPEED",   "lift",  "<pwm>|<v> MS|MMS",                    "travel speed as PWM, or in real units",                         false },
    { "SPEED?",  "lift",  "",                                    "the current speed setting, both ways",                          true },
    { "TIME",    "lift",  "[<stage>]",                           "alias of TIME?",                                                true },
    { "TIME?",   "lift",  "[<stage>]",                           "estimated travel time for one stage, or to a stage",            true },
    { "RGB",     "lift",  "<r> <g> <b>|BRIGHT <n>|EFFECT <name>", "LED strip colour, brightness or effect",                        false },
    { "PLAY",    "lift",  "<file>|STOP",                         "play mp3/wav from /music, or stop",                             false },
    { "VOL",     "lift",  "<0-100>",                             "audio volume",                                                  false },
    { "POSE",    "nong",  "<a1..a10> [T <ms>]",                  "move every joint; '-' keeps one where it is",                   false },
    { "POSE?",   "nong",  "",                                    "the current 10 joint angles",                                   true },
    { "JOINT",   "nong",  "<1-10|name> <deg> [T <ms>]",          "move one joint, by number or name",                             false },
    { "HOME",    "nong",  "[T <ms>]",                            "move to the neutral pose",                                      false },
    { "ZERO",    "nong",  "",                                    "alias of HOME",                                                 false },
    { "STOP",    "nong",  "",                                    "freeze mid-move; the pose holds",                               false },
    { "RELAX",   "nong",  "",                                    "unpower the servos so the arms can be posed by hand",           false },
    { "ATTACH",  "nong",  "",                                    "power the servos again, holding the current pose",              false },
    { "SPEED",   "nong",  "<deg_per_s>",                         "speed used when a POSE carries no T",                           false },
    { "SPEED?",  "nong",  "",                                    "the current speed in deg/s",                                    true },
    { "TIME",    "nong",  "[<a1..a10>]",                         "alias of TIME?",                                                true },
    { "TIME?",   "nong",  "[<a1..a10>]",                         "estimated and minimum duration of a move",                      true },
    { "SETZERO", "nong",  "",                                    "call the current pose home; trim absorbs it so nothing moves",  false },
    { "LIMIT",   "nong",  "<1-10|name> <min> <max>",             "how far that JOINT may turn",                                   false },
    { "LIMIT?",  "nong",  "",                                    "all limits, gear, pulse and travel as JSON",                    true },
    { "GEAR",    "nong",  "[<1-10|name|ALL> <pinion> <gear>]",   "per-joint reduction; no args reports every joint",              false },
    { "PULSE",   "nong",  "[<1-10|name|ALL> <min> <max> [dps]]", "per-joint servo pulse range in microseconds",                   false },
    { "RANGE",   "nong",  "[<1-10|name|ALL> <deg>]",             "per-joint SERVO travel (180/270) — not the joint's limits",     false },
    { "RATE",    "nong",  "[<1-10|name|ALL> <hz>]",              "per-joint servo frame rate",                                    false },
    { "SERVO",   "nong",  "[<1-10|name|ALL> <type>]",            "apply a servo preset from config/servos.json",                  false },
    { "JCFG",    "nong",  "<1-10|name> <pinion> <gear> <pmin> <pmax> <dps> <range> <hz> <min> <max>", "one joint's whole setup in a single line — what GEAR+PULSE+RANGE+RATE+LIMIT do in five", false },
    { "CAL",     "nong",  "[CLEAR]",                             "where the calibration is stored; CLEAR forgets it",             false },
};
static const int COMMAND_DOC_COUNT =
    sizeof(COMMAND_DOCS) / sizeof(COMMAND_DOCS[0]);

// Everything this board understands: core plus its own module type.
// ONE LINE, always.
//
// Every channel here is line-based: one command in, one reply line out. A
// multi-line reply poisons the NEXT command — its remaining lines are still
// arriving when that reply is read, so the caller gets a fragment of the
// previous answer. It happened for real on the bench: HELP printed 54 lines
// and the CAL after it came back as "-line status JSON".
//
// So bare HELP lists the NAMES, and HELP <name> explains exactly one.
inline String commandHelp(const String& type, const String& one = "") {
    String out;
    if (one.length()) {
        for (int i = 0; i < COMMAND_DOC_COUNT; i++) {
            const CommandDoc& d = COMMAND_DOCS[i];
            if (!one.equalsIgnoreCase(d.name)) continue;
            if (strcmp(d.scope, "core") && !type.equalsIgnoreCase(d.scope)) continue;
            out = String(d.name);
            if (strlen(d.args)) { out += ' '; out += d.args; }
            out += " - "; out += d.help;
            return out;
        }
        return String("no such command here: ") + one;
    }
    for (int i = 0; i < COMMAND_DOC_COUNT; i++) {
        const CommandDoc& d = COMMAND_DOCS[i];
        if (strcmp(d.scope, "core") && !type.equalsIgnoreCase(d.scope)) continue;
        if (out.length()) out += ' ';
        out += d.name;
    }
    return out + "  (HELP <name> for one)";
}
